export interface Destination {
  city: string;
  country: string;
  emoji: string;
  region: string;
}

export const DESTINATIONS: Destination[] = [
  // Asia
  { city: "Tokyo", country: "Japan", emoji: "\u{1F5FC}", region: "Asia" },
  { city: "Kyoto", country: "Japan", emoji: "\u26E9\uFE0F", region: "Asia" },
  { city: "Osaka", country: "Japan", emoji: "\u{1F3EF}", region: "Asia" },
  { city: "Bangkok", country: "Thailand", emoji: "\u{1F6D5}", region: "Asia" },
  { city: "Chiang Mai", country: "Thailand", emoji: "\u{1F418}", region: "Asia" },
  { city: "Phuket", country: "Thailand", emoji: "\u{1F3D6}\uFE0F", region: "Asia" },
  { city: "Bali", country: "Indonesia", emoji: "\u{1F30A}", region: "Asia" },
  { city: "Jakarta", country: "Indonesia", emoji: "\u{1F3D9}\uFE0F", region: "Asia" },
  { city: "Yogyakarta", country: "Indonesia", emoji: "\u{1F6D5}", region: "Asia" },
  { city: "Singapore", country: "Singapore", emoji: "\u{1F981}", region: "Asia" },
  { city: "Kuala Lumpur", country: "Malaysia", emoji: "\u{1F3D7}\uFE0F", region: "Asia" },
  { city: "Penang", country: "Malaysia", emoji: "\u{1F35C}", region: "Asia" },
  { city: "Langkawi", country: "Malaysia", emoji: "\u{1F3DD}\uFE0F", region: "Asia" },
  { city: "Seoul", country: "South Korea", emoji: "\u{1F3EF}", region: "Asia" },
  { city: "Busan", country: "South Korea", emoji: "\u{1F30A}", region: "Asia" },
  { city: "Hanoi", country: "Vietnam", emoji: "\u{1F3CD}\uFE0F", region: "Asia" },
  { city: "Ho Chi Minh City", country: "Vietnam", emoji: "\u{1F6F5}", region: "Asia" },
  { city: "Da Nang", country: "Vietnam", emoji: "\u{1F3D6}\uFE0F", region: "Asia" },
  { city: "Hong Kong", country: "China", emoji: "\u{1F307}", region: "Asia" },
  { city: "Shanghai", country: "China", emoji: "\u{1F3D9}\uFE0F", region: "Asia" },
  { city: "Beijing", country: "China", emoji: "\u{1F3EF}", region: "Asia" },
  { city: "Chengdu", country: "China", emoji: "\u{1F43C}", region: "Asia" },
  { city: "Xi'an", country: "China", emoji: "\u{1F3DB}\uFE0F", region: "Asia" },
  { city: "Taipei", country: "Taiwan", emoji: "\u{1F3EE}", region: "Asia" },
  { city: "Mumbai", country: "India", emoji: "\u{1F3D9}\uFE0F", region: "Asia" },
  { city: "Delhi", country: "India", emoji: "\u{1F54C}", region: "Asia" },
  { city: "Jaipur", country: "India", emoji: "\u{1F3F0}", region: "Asia" },
  { city: "Goa", country: "India", emoji: "\u{1F3D6}\uFE0F", region: "Asia" },
  { city: "Varanasi", country: "India", emoji: "\u{1F6D5}", region: "Asia" },
  { city: "Udaipur", country: "India", emoji: "\u{1F3F0}", region: "Asia" },
  { city: "Kerala", country: "India", emoji: "\u{1F334}", region: "Asia" },
  { city: "Kolkata", country: "India", emoji: "\u{1F3DB}\uFE0F", region: "Asia" },
  { city: "Chennai", country: "India", emoji: "\u{1F6D5}", region: "Asia" },
  { city: "Bangalore", country: "India", emoji: "\u{1F4BB}", region: "Asia" },
  { city: "Hyderabad", country: "India", emoji: "\u{1F3F0}", region: "Asia" },
  { city: "Agra", country: "India", emoji: "\u{1F54C}", region: "Asia" },
  { city: "Amritsar", country: "India", emoji: "\u{1F6D5}", region: "Asia" },
  { city: "Rishikesh", country: "India", emoji: "\u{1F9D8}", region: "Asia" },
  { city: "Shimla", country: "India", emoji: "\u{1F3D4}\uFE0F", region: "Asia" },
  { city: "Darjeeling", country: "India", emoji: "\u2615", region: "Asia" },
  { city: "Mysore", country: "India", emoji: "\u{1F3F0}", region: "Asia" },
  { city: "Pune", country: "India", emoji: "\u{1F3D9}\uFE0F", region: "Asia" },
  { city: "Ahmedabad", country: "India", emoji: "\u{1F54C}", region: "Asia" },
  { city: "Jodhpur", country: "India", emoji: "\u{1F3F0}", region: "Asia" },
  { city: "Kochi", country: "India", emoji: "\u{1F6F6}", region: "Asia" },
  { city: "Leh", country: "India", emoji: "\u{1F3D4}\uFE0F", region: "Asia" },
  { city: "Manali", country: "India", emoji: "\u2744\uFE0F", region: "Asia" },
  { city: "Kathmandu", country: "Nepal", emoji: "\u{1F3D4}\uFE0F", region: "Asia" },
  { city: "Pokhara", country: "Nepal", emoji: "\u{1F6F6}", region: "Asia" },
  { city: "Manila", country: "Philippines", emoji: "\u{1F3DD}\uFE0F", region: "Asia" },
  { city: "Cebu", country: "Philippines", emoji: "\u{1F30A}", region: "Asia" },
  { city: "Palawan", country: "Philippines", emoji: "\u{1F3DD}\uFE0F", region: "Asia" },
  { city: "Siem Reap", country: "Cambodia", emoji: "\u{1F6D5}", region: "Asia" },
  { city: "Phnom Penh", country: "Cambodia", emoji: "\u{1F3DB}\uFE0F", region: "Asia" },
  { city: "Luang Prabang", country: "Laos", emoji: "\u{1F6D5}", region: "Asia" },
  { city: "Yangon", country: "Myanmar", emoji: "\u{1F4FF}", region: "Asia" },
  { city: "Colombo", country: "Sri Lanka", emoji: "\u{1F3D6}\uFE0F", region: "Asia" },
  { city: "Maldives", country: "Maldives", emoji: "\u{1F3DD}\uFE0F", region: "Asia" },

  // Central Asia
  { city: "Samarkand", country: "Uzbekistan", emoji: "\u{1F54C}", region: "Asia" },
  { city: "Tbilisi", country: "Georgia", emoji: "\u{1F377}", region: "Asia" },
  { city: "Baku", country: "Azerbaijan", emoji: "\u{1F525}", region: "Asia" },

  // Europe
  { city: "Paris", country: "France", emoji: "\u{1F5FC}", region: "Europe" },
  { city: "Nice", country: "France", emoji: "\u2600\uFE0F", region: "Europe" },
  { city: "Lyon", country: "France", emoji: "\u{1F372}", region: "Europe" },
  { city: "Marseille", country: "France", emoji: "\u{1F6A2}", region: "Europe" },
  { city: "Bordeaux", country: "France", emoji: "\u{1F377}", region: "Europe" },
  { city: "Strasbourg", country: "France", emoji: "\u{1F3F0}", region: "Europe" },
  { city: "Toulouse", country: "France", emoji: "\u{1F680}", region: "Europe" },
  { city: "Montpellier", country: "France", emoji: "\u2600\uFE0F", region: "Europe" },
  { city: "Cannes", country: "France", emoji: "\u{1F3AC}", region: "Europe" },
  { city: "Normandy", country: "France", emoji: "\u{1F3D6}\uFE0F", region: "Europe" },
  { city: "Provence", country: "France", emoji: "\u{1F33B}", region: "Europe" },
  { city: "Chamonix", country: "France", emoji: "\u{1F3D4}\uFE0F", region: "Europe" },
  { city: "London", country: "United Kingdom", emoji: "\u{1F4F7}", region: "Europe" },
  { city: "Edinburgh", country: "United Kingdom", emoji: "\u{1F3F0}", region: "Europe" },
  { city: "Bath", country: "United Kingdom", emoji: "\u2668\uFE0F", region: "Europe" },
  { city: "Rome", country: "Italy", emoji: "\u{1F3DB}\uFE0F", region: "Europe" },
  { city: "Florence", country: "Italy", emoji: "\u{1F3A8}", region: "Europe" },
  { city: "Venice", country: "Italy", emoji: "\u{1F6F6}", region: "Europe" },
  { city: "Amalfi Coast", country: "Italy", emoji: "\u{1F30A}", region: "Europe" },
  { city: "Milan", country: "Italy", emoji: "\u{1F455}", region: "Europe" },
  { city: "Cinque Terre", country: "Italy", emoji: "\u{1F3D8}\uFE0F", region: "Europe" },
  { city: "Barcelona", country: "Spain", emoji: "\u{1F3D6}\uFE0F", region: "Europe" },
  { city: "Madrid", country: "Spain", emoji: "\u{1F483}", region: "Europe" },
  { city: "Seville", country: "Spain", emoji: "\u{1F33A}", region: "Europe" },
  { city: "Granada", country: "Spain", emoji: "\u{1F3F0}", region: "Europe" },
  { city: "San Sebastian", country: "Spain", emoji: "\u{1F37D}\uFE0F", region: "Europe" },
  { city: "Amsterdam", country: "Netherlands", emoji: "\u{1F6B2}", region: "Europe" },
  { city: "Berlin", country: "Germany", emoji: "\u{1F3DB}\uFE0F", region: "Europe" },
  { city: "Munich", country: "Germany", emoji: "\u{1F37A}", region: "Europe" },
  { city: "Hamburg", country: "Germany", emoji: "\u{1F6A2}", region: "Europe" },
  { city: "Frankfurt", country: "Germany", emoji: "\u{1F3E6}", region: "Europe" },
  { city: "Cologne", country: "Germany", emoji: "\u{1F3DB}\uFE0F", region: "Europe" },
  { city: "Dresden", country: "Germany", emoji: "\u{1F3A8}", region: "Europe" },
  { city: "Heidelberg", country: "Germany", emoji: "\u{1F3F0}", region: "Europe" },
  { city: "Dusseldorf", country: "Germany", emoji: "\u{1F3D9}\uFE0F", region: "Europe" },
  { city: "Black Forest", country: "Germany", emoji: "\u{1F332}", region: "Europe" },
  { city: "Prague", country: "Czech Republic", emoji: "\u{1F3F0}", region: "Europe" },
  { city: "Vienna", country: "Austria", emoji: "\u{1F3B6}", region: "Europe" },
  { city: "Salzburg", country: "Austria", emoji: "\u{1F3B5}", region: "Europe" },
  { city: "Zurich", country: "Switzerland", emoji: "\u{1F3D4}\uFE0F", region: "Europe" },
  { city: "Interlaken", country: "Switzerland", emoji: "\u{1F3D4}\uFE0F", region: "Europe" },
  { city: "Istanbul", country: "Turkey", emoji: "\u{1F54C}", region: "Europe" },
  { city: "Cappadocia", country: "Turkey", emoji: "\u{1F388}", region: "Europe" },
  { city: "Santorini", country: "Greece", emoji: "\u{1F3D6}\uFE0F", region: "Europe" },
  { city: "Athens", country: "Greece", emoji: "\u{1F3DB}\uFE0F", region: "Europe" },
  { city: "Mykonos", country: "Greece", emoji: "\u{1F3D6}\uFE0F", region: "Europe" },
  { city: "Crete", country: "Greece", emoji: "\u{1F30A}", region: "Europe" },
  { city: "Lisbon", country: "Portugal", emoji: "\u{1F6A2}", region: "Europe" },
  { city: "Porto", country: "Portugal", emoji: "\u{1F377}", region: "Europe" },
  { city: "Dublin", country: "Ireland", emoji: "\u2618\uFE0F", region: "Europe" },
  { city: "Copenhagen", country: "Denmark", emoji: "\u{1F6B2}", region: "Europe" },
  { city: "Stockholm", country: "Sweden", emoji: "\u2744\uFE0F", region: "Europe" },
  { city: "Oslo", country: "Norway", emoji: "\u{1F3D4}\uFE0F", region: "Europe" },
  { city: "Bergen", country: "Norway", emoji: "\u{1F6A2}", region: "Europe" },
  { city: "Helsinki", country: "Finland", emoji: "\u2744\uFE0F", region: "Europe" },
  { city: "Budapest", country: "Hungary", emoji: "\u2668\uFE0F", region: "Europe" },
  { city: "Dubrovnik", country: "Croatia", emoji: "\u{1F3F0}", region: "Europe" },
  { city: "Split", country: "Croatia", emoji: "\u{1F3DB}\uFE0F", region: "Europe" },
  { city: "Reykjavik", country: "Iceland", emoji: "\u{1F30B}", region: "Europe" },
  { city: "Krakow", country: "Poland", emoji: "\u{1F3F0}", region: "Europe" },
  { city: "Warsaw", country: "Poland", emoji: "\u{1F3D9}\uFE0F", region: "Europe" },
  { city: "Bruges", country: "Belgium", emoji: "\u{1F36B}", region: "Europe" },
  { city: "Brussels", country: "Belgium", emoji: "\u{1F9C7}", region: "Europe" },
  { city: "Tallinn", country: "Estonia", emoji: "\u{1F3F0}", region: "Europe" },
  { city: "Riga", country: "Latvia", emoji: "\u{1F3DB}\uFE0F", region: "Europe" },
  { city: "Bucharest", country: "Romania", emoji: "\u{1F3F0}", region: "Europe" },
  { city: "Sofia", country: "Bulgaria", emoji: "\u{1F54C}", region: "Europe" },
  { city: "Montenegro", country: "Montenegro", emoji: "\u{1F3D4}\uFE0F", region: "Europe" },
  { city: "Malta", country: "Malta", emoji: "\u{1F3F0}", region: "Europe" },
  { city: "Moscow", country: "Russia", emoji: "\u{1F3F0}", region: "Europe" },
  { city: "St. Petersburg", country: "Russia", emoji: "\u{1F3DB}\uFE0F", region: "Europe" },
  { city: "Kazan", country: "Russia", emoji: "\u{1F54C}", region: "Europe" },
  { city: "Sochi", country: "Russia", emoji: "\u{1F3D6}\uFE0F", region: "Europe" },
  { city: "Vladivostok", country: "Russia", emoji: "\u{1F309}", region: "Europe" },
  { city: "Novosibirsk", country: "Russia", emoji: "\u2744\uFE0F", region: "Europe" },
  { city: "Yekaterinburg", country: "Russia", emoji: "\u{1F3D9}\uFE0F", region: "Europe" },
  { city: "Kaliningrad", country: "Russia", emoji: "\u{1F3F0}", region: "Europe" },

  // Americas
  { city: "New York", country: "United States", emoji: "\u{1F5FD}", region: "Americas" },
  { city: "San Francisco", country: "United States", emoji: "\u{1F309}", region: "Americas" },
  { city: "Los Angeles", country: "United States", emoji: "\u{1F3AC}", region: "Americas" },
  { city: "Miami", country: "United States", emoji: "\u{1F334}", region: "Americas" },
  { city: "New Orleans", country: "United States", emoji: "\u{1F3B7}", region: "Americas" },
  { city: "Honolulu", country: "United States", emoji: "\u{1F3C4}", region: "Americas" },
  { city: "Chicago", country: "United States", emoji: "\u{1F3D9}\uFE0F", region: "Americas" },
  { city: "Las Vegas", country: "United States", emoji: "\u{1F3B0}", region: "Americas" },
  { city: "Washington D.C.", country: "United States", emoji: "\u{1F3DB}\uFE0F", region: "Americas" },
  { city: "Nashville", country: "United States", emoji: "\u{1F3B5}", region: "Americas" },
  { city: "Seattle", country: "United States", emoji: "\u2615", region: "Americas" },
  { city: "Cancun", country: "Mexico", emoji: "\u{1F3D6}\uFE0F", region: "Americas" },
  { city: "Mexico City", country: "Mexico", emoji: "\u{1F32E}", region: "Americas" },
  { city: "Oaxaca", country: "Mexico", emoji: "\u{1F336}\uFE0F", region: "Americas" },
  { city: "Tulum", country: "Mexico", emoji: "\u{1F6D5}", region: "Americas" },
  { city: "Rio de Janeiro", country: "Brazil", emoji: "\u{1F3D6}\uFE0F", region: "Americas" },
  { city: "Sao Paulo", country: "Brazil", emoji: "\u{1F3D9}\uFE0F", region: "Americas" },
  { city: "Buenos Aires", country: "Argentina", emoji: "\u{1F483}", region: "Americas" },
  { city: "Patagonia", country: "Argentina", emoji: "\u{1F3D4}\uFE0F", region: "Americas" },
  { city: "Cusco", country: "Peru", emoji: "\u{1F3D4}\uFE0F", region: "Americas" },
  { city: "Lima", country: "Peru", emoji: "\u{1F37D}\uFE0F", region: "Americas" },
  { city: "Bogota", country: "Colombia", emoji: "\u{1F3D9}\uFE0F", region: "Americas" },
  { city: "Medellin", country: "Colombia", emoji: "\u{1F338}", region: "Americas" },
  { city: "Cartagena", country: "Colombia", emoji: "\u{1F3F0}", region: "Americas" },
  { city: "Havana", country: "Cuba", emoji: "\u{1F697}", region: "Americas" },
  { city: "Santiago", country: "Chile", emoji: "\u{1F3D4}\uFE0F", region: "Americas" },
  { city: "Montevideo", country: "Uruguay", emoji: "\u{1F30A}", region: "Americas" },
  { city: "Quito", country: "Ecuador", emoji: "\u{1F30B}", region: "Americas" },
  { city: "San Jose", country: "Costa Rica", emoji: "\u{1F99C}", region: "Americas" },
  { city: "Panama City", country: "Panama", emoji: "\u{1F6A2}", region: "Americas" },
  { city: "Toronto", country: "Canada", emoji: "\u{1F341}", region: "Americas" },
  { city: "Vancouver", country: "Canada", emoji: "\u{1F3D4}\uFE0F", region: "Americas" },
  { city: "Montreal", country: "Canada", emoji: "\u{1F3A8}", region: "Americas" },
  { city: "Banff", country: "Canada", emoji: "\u{1F3D4}\uFE0F", region: "Americas" },

  // Caribbean
  { city: "Punta Cana", country: "Dominican Republic", emoji: "\u{1F334}", region: "Americas" },
  { city: "Jamaica", country: "Jamaica", emoji: "\u{1F3B6}", region: "Americas" },
  { city: "Aruba", country: "Aruba", emoji: "\u{1F3D6}\uFE0F", region: "Americas" },
  { city: "Barbados", country: "Barbados", emoji: "\u{1F3DD}\uFE0F", region: "Americas" },
  { city: "St. Lucia", country: "St. Lucia", emoji: "\u{1F30B}", region: "Americas" },

  // Middle East
  { city: "Dubai", country: "UAE", emoji: "\u{1F3D9}\uFE0F", region: "Middle East" },
  { city: "Abu Dhabi", country: "UAE", emoji: "\u{1F54C}", region: "Middle East" },
  { city: "Sharjah", country: "UAE", emoji: "\u{1F3DB}\uFE0F", region: "Middle East" },
  { city: "Ajman", country: "UAE", emoji: "\u{1F3D6}\uFE0F", region: "Middle East" },
  { city: "Ras Al Khaimah", country: "UAE", emoji: "\u{1F3D4}\uFE0F", region: "Middle East" },
  { city: "Fujairah", country: "UAE", emoji: "\u{1F30A}", region: "Middle East" },
  { city: "Al Ain", country: "UAE", emoji: "\u{1F3DC}\uFE0F", region: "Middle East" },
  { city: "Doha", country: "Qatar", emoji: "\u{1F3D9}\uFE0F", region: "Middle East" },
  { city: "Muscat", country: "Oman", emoji: "\u{1F3DC}\uFE0F", region: "Middle East" },
  { city: "Amman", country: "Jordan", emoji: "\u{1F3DB}\uFE0F", region: "Middle East" },
  { city: "Petra", country: "Jordan", emoji: "\u{1F3DC}\uFE0F", region: "Middle East" },
  { city: "Tel Aviv", country: "Israel", emoji: "\u{1F3D6}\uFE0F", region: "Middle East" },
  { city: "Jerusalem", country: "Israel", emoji: "\u{1F54D}", region: "Middle East" },

  // Africa
  { city: "Marrakech", country: "Morocco", emoji: "\u{1F3EE}", region: "Africa" },
  { city: "Fez", country: "Morocco", emoji: "\u{1F54C}", region: "Africa" },
  { city: "Cape Town", country: "South Africa", emoji: "\u{1F3D4}\uFE0F", region: "Africa" },
  { city: "Johannesburg", country: "South Africa", emoji: "\u{1F3D9}\uFE0F", region: "Africa" },
  { city: "Nairobi", country: "Kenya", emoji: "\u{1F981}", region: "Africa" },
  { city: "Cairo", country: "Egypt", emoji: "\u{1F3DB}\uFE0F", region: "Africa" },
  { city: "Luxor", country: "Egypt", emoji: "\u{1F3DB}\uFE0F", region: "Africa" },
  { city: "Zanzibar", country: "Tanzania", emoji: "\u{1F3D6}\uFE0F", region: "Africa" },
  { city: "Serengeti", country: "Tanzania", emoji: "\u{1F981}", region: "Africa" },
  { city: "Victoria Falls", country: "Zimbabwe", emoji: "\u{1F30A}", region: "Africa" },
  { city: "Accra", country: "Ghana", emoji: "\u{1F3D9}\uFE0F", region: "Africa" },
  { city: "Dakar", country: "Senegal", emoji: "\u{1F3B6}", region: "Africa" },
  { city: "Kigali", country: "Rwanda", emoji: "\u{1F33F}", region: "Africa" },
  { city: "Madagascar", country: "Madagascar", emoji: "\u{1F334}", region: "Africa" },
  { city: "Mauritius", country: "Mauritius", emoji: "\u{1F3DD}\uFE0F", region: "Africa" },

  // Oceania
  { city: "Sydney", country: "Australia", emoji: "\u{1F3A1}", region: "Oceania" },
  { city: "Melbourne", country: "Australia", emoji: "\u2615", region: "Oceania" },
  { city: "Brisbane", country: "Australia", emoji: "\u{1F33A}", region: "Oceania" },
  { city: "Perth", country: "Australia", emoji: "\u2600\uFE0F", region: "Oceania" },
  { city: "Great Barrier Reef", country: "Australia", emoji: "\u{1F420}", region: "Oceania" },
  { city: "Auckland", country: "New Zealand", emoji: "\u{1F3D4}\uFE0F", region: "Oceania" },
  { city: "Queenstown", country: "New Zealand", emoji: "\u{1F3BF}", region: "Oceania" },
  { city: "Rotorua", country: "New Zealand", emoji: "\u2668\uFE0F", region: "Oceania" },
  { city: "Fiji", country: "Fiji", emoji: "\u{1F3DD}\uFE0F", region: "Oceania" },
  { city: "Bora Bora", country: "French Polynesia", emoji: "\u{1F3DD}\uFE0F", region: "Oceania" },
  { city: "Tahiti", country: "French Polynesia", emoji: "\u{1F30A}", region: "Oceania" },
];

export function searchDestinations(query: string): Destination[] {
  if (!query || query.length < 1) return [];
  const q = query.toLowerCase();
  return DESTINATIONS.filter(
    (d) =>
      d.city.toLowerCase().includes(q) ||
      d.country.toLowerCase().includes(q) ||
      d.region.toLowerCase().includes(q)
  ).slice(0, 8);
}
